#! /bin/sh
fixaudio &
pkill sxhkd
sxhkd &
xsetroot -cursor_name left_ptr &

pkill picom
picom --config /home/reithe/.config/picom/picom.conf &
#nitrogen --restore &
feh --bg-fill --randomize ~/Pictures/walls/* &
#wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1 &

killall bspwm_nobor bspc xfce4-panel
~/.config/bspwm/scripts/bspwm_noborder &
#polybar -q main -c
bspc monitor VGA-1 -d I II III IV V
~/polybar-collection/launch.sh &

bspc config pointer_modifier mod1
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

#bspc monitor -d I II III IV V

bspc rule -a galculator state=floating
bspc rule -a discord state=floating
bspc rule -a GLava state=floating
bspc rule -a mpv state=floating
bspc rule -a zenity state=floating
bspc rule -a AppRun.wrapped state=floating



#bspc monitor LVDS1 -d I II III IV V
#bspc monitor VGA1 -d VI VII VIII IX X

bspc config border_width          0
bspc config active border_width   0
bspc config normal border_width   0
#bspc config active_border_color "#000000"
bspc config focused_border_color "#1f8999"
#bspc config normal_border_color "#1F8999"
bspc config window_gap           12

bspc config split_ratio          0.52
#bspc config border_radius        10
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config top_padding             1

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a burp-StartBurp: state=floating

bspc config focus_follows_pointer true
bspc config pointer_motion_interval 40

picom --experimental-backends -b

